[tool.poetry]
name = "chat-history"
version = "0.1.0"
description = ""
authors = ["Dima Kuchin <dima@mirable.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.1"
uvicorn = "^0.23.2"
markdown = "^3.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
